//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TimeOutOhm {
            get {
                return ((int)(this["TimeOutOhm"]));
            }
            set {
                this["TimeOutOhm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TimeOutV {
            get {
                return ((int)(this["TimeOutV"]));
            }
            set {
                this["TimeOutV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimeOutHz {
            get {
                return ((int)(this["TimeOutHz"]));
            }
            set {
                this["TimeOutHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FullLogPath {
            get {
                return ((string)(this["FullLogPath"]));
            }
            set {
                this["FullLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUseAverageValue {
            get {
                return ((bool)(this["IsUseAverageValue"]));
            }
            set {
                this["IsUseAverageValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CountAverageValue {
            get {
                return ((int)(this["CountAverageValue"]));
            }
            set {
                this["CountAverageValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string FlukeComPort {
            get {
                return ((string)(this["FlukeComPort"]));
            }
            set {
                this["FlukeComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string CommComPort {
            get {
                return ((string)(this["CommComPort"]));
            }
            set {
                this["CommComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string Sc1ComPort {
            get {
                return ((string)(this["Sc1ComPort"]));
            }
            set {
                this["Sc1ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string Sc2ComPort {
            get {
                return ((string)(this["Sc2ComPort"]));
            }
            set {
                this["Sc2ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string Sc3ComPort {
            get {
                return ((string)(this["Sc3ComPort"]));
            }
            set {
                this["Sc3ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string Sc4ComPort {
            get {
                return ((string)(this["Sc4ComPort"]));
            }
            set {
                this["Sc4ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string Sc5ComPort {
            get {
                return ((string)(this["Sc5ComPort"]));
            }
            set {
                this["Sc5ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string Sc6ComPort {
            get {
                return ((string)(this["Sc6ComPort"]));
            }
            set {
                this["Sc6ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch0Ohm80IsActive {
            get {
                return ((bool)(this["Ch0Ohm80IsActive"]));
            }
            set {
                this["Ch0Ohm80IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch0Ohm90IsActive {
            get {
                return ((bool)(this["Ch0Ohm90IsActive"]));
            }
            set {
                this["Ch0Ohm90IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch0Ohm100IsActive {
            get {
                return ((bool)(this["Ch0Ohm100IsActive"]));
            }
            set {
                this["Ch0Ohm100IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch0Ohm115IsActive {
            get {
                return ((bool)(this["Ch0Ohm115IsActive"]));
            }
            set {
                this["Ch0Ohm115IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch0Ohm130IsActive {
            get {
                return ((bool)(this["Ch0Ohm130IsActive"]));
            }
            set {
                this["Ch0Ohm130IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch0Ohm140IsActive {
            get {
                return ((bool)(this["Ch0Ohm140IsActive"]));
            }
            set {
                this["Ch0Ohm140IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch1Ohm80IsActive {
            get {
                return ((bool)(this["Ch1Ohm80IsActive"]));
            }
            set {
                this["Ch1Ohm80IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch1Ohm90IsActive {
            get {
                return ((bool)(this["Ch1Ohm90IsActive"]));
            }
            set {
                this["Ch1Ohm90IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch1Ohm100IsActive {
            get {
                return ((bool)(this["Ch1Ohm100IsActive"]));
            }
            set {
                this["Ch1Ohm100IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch1Ohm115IsActive {
            get {
                return ((bool)(this["Ch1Ohm115IsActive"]));
            }
            set {
                this["Ch1Ohm115IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch1Ohm130IsActive {
            get {
                return ((bool)(this["Ch1Ohm130IsActive"]));
            }
            set {
                this["Ch1Ohm130IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch1Ohm140IsActive {
            get {
                return ((bool)(this["Ch1Ohm140IsActive"]));
            }
            set {
                this["Ch1Ohm140IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch2Ohm80IsActive {
            get {
                return ((bool)(this["Ch2Ohm80IsActive"]));
            }
            set {
                this["Ch2Ohm80IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch2Ohm90IsActive {
            get {
                return ((bool)(this["Ch2Ohm90IsActive"]));
            }
            set {
                this["Ch2Ohm90IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch2Ohm100IsActive {
            get {
                return ((bool)(this["Ch2Ohm100IsActive"]));
            }
            set {
                this["Ch2Ohm100IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch2Ohm115IsActive {
            get {
                return ((bool)(this["Ch2Ohm115IsActive"]));
            }
            set {
                this["Ch2Ohm115IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch2Ohm130IsActive {
            get {
                return ((bool)(this["Ch2Ohm130IsActive"]));
            }
            set {
                this["Ch2Ohm130IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch2Ohm140IsActive {
            get {
                return ((bool)(this["Ch2Ohm140IsActive"]));
            }
            set {
                this["Ch2Ohm140IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch3V1IsActive {
            get {
                return ((bool)(this["Ch3V1IsActive"]));
            }
            set {
                this["Ch3V1IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch3V2IsActive {
            get {
                return ((bool)(this["Ch3V2IsActive"]));
            }
            set {
                this["Ch3V2IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch3V3IsActive {
            get {
                return ((bool)(this["Ch3V3IsActive"]));
            }
            set {
                this["Ch3V3IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch3V4IsActive {
            get {
                return ((bool)(this["Ch3V4IsActive"]));
            }
            set {
                this["Ch3V4IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch3V5IsActive {
            get {
                return ((bool)(this["Ch3V5IsActive"]));
            }
            set {
                this["Ch3V5IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch5V1IsActive {
            get {
                return ((bool)(this["Ch5V1IsActive"]));
            }
            set {
                this["Ch5V1IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch5V2IsActive {
            get {
                return ((bool)(this["Ch5V2IsActive"]));
            }
            set {
                this["Ch5V2IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch5V3IsActive {
            get {
                return ((bool)(this["Ch5V3IsActive"]));
            }
            set {
                this["Ch5V3IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch5V4IsActive {
            get {
                return ((bool)(this["Ch5V4IsActive"]));
            }
            set {
                this["Ch5V4IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch5V5IsActive {
            get {
                return ((bool)(this["Ch5V5IsActive"]));
            }
            set {
                this["Ch5V5IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch6Hz5IsActive {
            get {
                return ((bool)(this["Ch6Hz5IsActive"]));
            }
            set {
                this["Ch6Hz5IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch6Hz25IsActive {
            get {
                return ((bool)(this["Ch6Hz25IsActive"]));
            }
            set {
                this["Ch6Hz25IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch6Hz50IsActive {
            get {
                return ((bool)(this["Ch6Hz50IsActive"]));
            }
            set {
                this["Ch6Hz50IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch6Hz75IsActive {
            get {
                return ((bool)(this["Ch6Hz75IsActive"]));
            }
            set {
                this["Ch6Hz75IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch6Hz100IsActive {
            get {
                return ((bool)(this["Ch6Hz100IsActive"]));
            }
            set {
                this["Ch6Hz100IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc1Ch0Error {
            get {
                return ((decimal)(this["Sc1Ch0Error"]));
            }
            set {
                this["Sc1Ch0Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc2Ch0Error {
            get {
                return ((decimal)(this["Sc2Ch0Error"]));
            }
            set {
                this["Sc2Ch0Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc3Ch0Error {
            get {
                return ((decimal)(this["Sc3Ch0Error"]));
            }
            set {
                this["Sc3Ch0Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc4Ch0Error {
            get {
                return ((decimal)(this["Sc4Ch0Error"]));
            }
            set {
                this["Sc4Ch0Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc5Ch0Error {
            get {
                return ((decimal)(this["Sc5Ch0Error"]));
            }
            set {
                this["Sc5Ch0Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc6Ch0Error {
            get {
                return ((decimal)(this["Sc6Ch0Error"]));
            }
            set {
                this["Sc6Ch0Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc1Ch1Error {
            get {
                return ((decimal)(this["Sc1Ch1Error"]));
            }
            set {
                this["Sc1Ch1Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc2Ch1Error {
            get {
                return ((decimal)(this["Sc2Ch1Error"]));
            }
            set {
                this["Sc2Ch1Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc3Ch1Error {
            get {
                return ((decimal)(this["Sc3Ch1Error"]));
            }
            set {
                this["Sc3Ch1Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc4Ch1Error {
            get {
                return ((decimal)(this["Sc4Ch1Error"]));
            }
            set {
                this["Sc4Ch1Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc5Ch1Error {
            get {
                return ((decimal)(this["Sc5Ch1Error"]));
            }
            set {
                this["Sc5Ch1Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc6Ch1Error {
            get {
                return ((decimal)(this["Sc6Ch1Error"]));
            }
            set {
                this["Sc6Ch1Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc1Ch2Error {
            get {
                return ((decimal)(this["Sc1Ch2Error"]));
            }
            set {
                this["Sc1Ch2Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc2Ch2Error {
            get {
                return ((decimal)(this["Sc2Ch2Error"]));
            }
            set {
                this["Sc2Ch2Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc3Ch2Error {
            get {
                return ((decimal)(this["Sc3Ch2Error"]));
            }
            set {
                this["Sc3Ch2Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc4Ch2Error {
            get {
                return ((decimal)(this["Sc4Ch2Error"]));
            }
            set {
                this["Sc4Ch2Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc5Ch2Error {
            get {
                return ((decimal)(this["Sc5Ch2Error"]));
            }
            set {
                this["Sc5Ch2Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc6Ch2Error {
            get {
                return ((decimal)(this["Sc6Ch2Error"]));
            }
            set {
                this["Sc6Ch2Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc1Ch3Error {
            get {
                return ((decimal)(this["Sc1Ch3Error"]));
            }
            set {
                this["Sc1Ch3Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc2Ch3Error {
            get {
                return ((decimal)(this["Sc2Ch3Error"]));
            }
            set {
                this["Sc2Ch3Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc3Ch3Error {
            get {
                return ((decimal)(this["Sc3Ch3Error"]));
            }
            set {
                this["Sc3Ch3Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc4Ch3Error {
            get {
                return ((decimal)(this["Sc4Ch3Error"]));
            }
            set {
                this["Sc4Ch3Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc5Ch3Error {
            get {
                return ((decimal)(this["Sc5Ch3Error"]));
            }
            set {
                this["Sc5Ch3Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc6Ch3Error {
            get {
                return ((decimal)(this["Sc6Ch3Error"]));
            }
            set {
                this["Sc6Ch3Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc1Ch5Error {
            get {
                return ((decimal)(this["Sc1Ch5Error"]));
            }
            set {
                this["Sc1Ch5Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc2Ch5Error {
            get {
                return ((decimal)(this["Sc2Ch5Error"]));
            }
            set {
                this["Sc2Ch5Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc3Ch5Error {
            get {
                return ((decimal)(this["Sc3Ch5Error"]));
            }
            set {
                this["Sc3Ch5Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc4Ch5Error {
            get {
                return ((decimal)(this["Sc4Ch5Error"]));
            }
            set {
                this["Sc4Ch5Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc5Ch5Error {
            get {
                return ((decimal)(this["Sc5Ch5Error"]));
            }
            set {
                this["Sc5Ch5Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc6Ch5Error {
            get {
                return ((decimal)(this["Sc6Ch5Error"]));
            }
            set {
                this["Sc6Ch5Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc1Ch6Error {
            get {
                return ((decimal)(this["Sc1Ch6Error"]));
            }
            set {
                this["Sc1Ch6Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc2Ch6Error {
            get {
                return ((decimal)(this["Sc2Ch6Error"]));
            }
            set {
                this["Sc2Ch6Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc3Ch6Error {
            get {
                return ((decimal)(this["Sc3Ch6Error"]));
            }
            set {
                this["Sc3Ch6Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc4Ch6Error {
            get {
                return ((decimal)(this["Sc4Ch6Error"]));
            }
            set {
                this["Sc4Ch6Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc5Ch6Error {
            get {
                return ((decimal)(this["Sc5Ch6Error"]));
            }
            set {
                this["Sc5Ch6Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc6Ch6Error {
            get {
                return ((decimal)(this["Sc6Ch6Error"]));
            }
            set {
                this["Sc6Ch6Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ScVersion {
            get {
                return ((int)(this["ScVersion"]));
            }
            set {
                this["ScVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsOnCalibration {
            get {
                return ((bool)(this["IsOnCalibration"]));
            }
            set {
                this["IsOnCalibration"] = value;
            }
        }
    }
}
