//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TimeOutOhm {
            get {
                return ((int)(this["TimeOutOhm"]));
            }
            set {
                this["TimeOutOhm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TimeOutV {
            get {
                return ((int)(this["TimeOutV"]));
            }
            set {
                this["TimeOutV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimeOutHz {
            get {
                return ((int)(this["TimeOutHz"]));
            }
            set {
                this["TimeOutHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FullLogPath {
            get {
                return ((string)(this["FullLogPath"]));
            }
            set {
                this["FullLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUseAverageValue {
            get {
                return ((bool)(this["IsUseAverageValue"]));
            }
            set {
                this["IsUseAverageValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CountAverageValue {
            get {
                return ((int)(this["CountAverageValue"]));
            }
            set {
                this["CountAverageValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string FlukeComPort {
            get {
                return ((string)(this["FlukeComPort"]));
            }
            set {
                this["FlukeComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string CommComPort {
            get {
                return ((string)(this["CommComPort"]));
            }
            set {
                this["CommComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string Mac1ComPort {
            get {
                return ((string)(this["Mac1ComPort"]));
            }
            set {
                this["Mac1ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string Mac2ComPort {
            get {
                return ((string)(this["Mac2ComPort"]));
            }
            set {
                this["Mac2ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string Mac3ComPort {
            get {
                return ((string)(this["Mac3ComPort"]));
            }
            set {
                this["Mac3ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string Mac4ComPort {
            get {
                return ((string)(this["Mac4ComPort"]));
            }
            set {
                this["Mac4ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string Mac5ComPort {
            get {
                return ((string)(this["Mac5ComPort"]));
            }
            set {
                this["Mac5ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Не выбрано")]
        public string Mac6ComPort {
            get {
                return ((string)(this["Mac6ComPort"]));
            }
            set {
                this["Mac6ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch0Ohm1IsActive {
            get {
                return ((bool)(this["Ch0Ohm1IsActive"]));
            }
            set {
                this["Ch0Ohm1IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch0Ohm2IsActive {
            get {
                return ((bool)(this["Ch0Ohm2IsActive"]));
            }
            set {
                this["Ch0Ohm2IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch0Ohm3IsActive {
            get {
                return ((bool)(this["Ch0Ohm3IsActive"]));
            }
            set {
                this["Ch0Ohm3IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch0Ohm4IsActive {
            get {
                return ((bool)(this["Ch0Ohm4IsActive"]));
            }
            set {
                this["Ch0Ohm4IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch0Ohm5IsActive {
            get {
                return ((bool)(this["Ch0Ohm5IsActive"]));
            }
            set {
                this["Ch0Ohm5IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch1Ohm1IsActive {
            get {
                return ((bool)(this["Ch1Ohm1IsActive"]));
            }
            set {
                this["Ch1Ohm1IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch1Ohm2IsActive {
            get {
                return ((bool)(this["Ch1Ohm2IsActive"]));
            }
            set {
                this["Ch1Ohm2IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch1Ohm3IsActive {
            get {
                return ((bool)(this["Ch1Ohm3IsActive"]));
            }
            set {
                this["Ch1Ohm3IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch1Ohm4IsActive {
            get {
                return ((bool)(this["Ch1Ohm4IsActive"]));
            }
            set {
                this["Ch1Ohm4IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch1Ohm5IsActive {
            get {
                return ((bool)(this["Ch1Ohm5IsActive"]));
            }
            set {
                this["Ch1Ohm5IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch2Ohm1IsActive {
            get {
                return ((bool)(this["Ch2Ohm1IsActive"]));
            }
            set {
                this["Ch2Ohm1IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch2Ohm2IsActive {
            get {
                return ((bool)(this["Ch2Ohm2IsActive"]));
            }
            set {
                this["Ch2Ohm2IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch2Ohm3IsActive {
            get {
                return ((bool)(this["Ch2Ohm3IsActive"]));
            }
            set {
                this["Ch2Ohm3IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch2Ohm4IsActive {
            get {
                return ((bool)(this["Ch2Ohm4IsActive"]));
            }
            set {
                this["Ch2Ohm4IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch2Ohm5IsActive {
            get {
                return ((bool)(this["Ch2Ohm5IsActive"]));
            }
            set {
                this["Ch2Ohm5IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch3V1IsActive {
            get {
                return ((bool)(this["Ch3V1IsActive"]));
            }
            set {
                this["Ch3V1IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch3V2IsActive {
            get {
                return ((bool)(this["Ch3V2IsActive"]));
            }
            set {
                this["Ch3V2IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch3V3IsActive {
            get {
                return ((bool)(this["Ch3V3IsActive"]));
            }
            set {
                this["Ch3V3IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch3V4IsActive {
            get {
                return ((bool)(this["Ch3V4IsActive"]));
            }
            set {
                this["Ch3V4IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch3V5IsActive {
            get {
                return ((bool)(this["Ch3V5IsActive"]));
            }
            set {
                this["Ch3V5IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch5V1IsActive {
            get {
                return ((bool)(this["Ch5V1IsActive"]));
            }
            set {
                this["Ch5V1IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch5V2IsActive {
            get {
                return ((bool)(this["Ch5V2IsActive"]));
            }
            set {
                this["Ch5V2IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch5V3IsActive {
            get {
                return ((bool)(this["Ch5V3IsActive"]));
            }
            set {
                this["Ch5V3IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch5V4IsActive {
            get {
                return ((bool)(this["Ch5V4IsActive"]));
            }
            set {
                this["Ch5V4IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch5V5IsActive {
            get {
                return ((bool)(this["Ch5V5IsActive"]));
            }
            set {
                this["Ch5V5IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch6Hz1IsActive {
            get {
                return ((bool)(this["Ch6Hz1IsActive"]));
            }
            set {
                this["Ch6Hz1IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch6Hz2IsActive {
            get {
                return ((bool)(this["Ch6Hz2IsActive"]));
            }
            set {
                this["Ch6Hz2IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch6Hz3IsActive {
            get {
                return ((bool)(this["Ch6Hz3IsActive"]));
            }
            set {
                this["Ch6Hz3IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch6Hz4IsActive {
            get {
                return ((bool)(this["Ch6Hz4IsActive"]));
            }
            set {
                this["Ch6Hz4IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ch6Hz5IsActive {
            get {
                return ((bool)(this["Ch6Hz5IsActive"]));
            }
            set {
                this["Ch6Hz5IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc1Ch0Error {
            get {
                return ((decimal)(this["Sc1Ch0Error"]));
            }
            set {
                this["Sc1Ch0Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc2Ch0Error {
            get {
                return ((decimal)(this["Sc2Ch0Error"]));
            }
            set {
                this["Sc2Ch0Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc3Ch0Error {
            get {
                return ((decimal)(this["Sc3Ch0Error"]));
            }
            set {
                this["Sc3Ch0Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc4Ch0Error {
            get {
                return ((decimal)(this["Sc4Ch0Error"]));
            }
            set {
                this["Sc4Ch0Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc5Ch0Error {
            get {
                return ((decimal)(this["Sc5Ch0Error"]));
            }
            set {
                this["Sc5Ch0Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc6Ch0Error {
            get {
                return ((decimal)(this["Sc6Ch0Error"]));
            }
            set {
                this["Sc6Ch0Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc1Ch1Error {
            get {
                return ((decimal)(this["Sc1Ch1Error"]));
            }
            set {
                this["Sc1Ch1Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc2Ch1Error {
            get {
                return ((decimal)(this["Sc2Ch1Error"]));
            }
            set {
                this["Sc2Ch1Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc3Ch1Error {
            get {
                return ((decimal)(this["Sc3Ch1Error"]));
            }
            set {
                this["Sc3Ch1Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc4Ch1Error {
            get {
                return ((decimal)(this["Sc4Ch1Error"]));
            }
            set {
                this["Sc4Ch1Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc5Ch1Error {
            get {
                return ((decimal)(this["Sc5Ch1Error"]));
            }
            set {
                this["Sc5Ch1Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc6Ch1Error {
            get {
                return ((decimal)(this["Sc6Ch1Error"]));
            }
            set {
                this["Sc6Ch1Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc1Ch2Error {
            get {
                return ((decimal)(this["Sc1Ch2Error"]));
            }
            set {
                this["Sc1Ch2Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc2Ch2Error {
            get {
                return ((decimal)(this["Sc2Ch2Error"]));
            }
            set {
                this["Sc2Ch2Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc3Ch2Error {
            get {
                return ((decimal)(this["Sc3Ch2Error"]));
            }
            set {
                this["Sc3Ch2Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc4Ch2Error {
            get {
                return ((decimal)(this["Sc4Ch2Error"]));
            }
            set {
                this["Sc4Ch2Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc5Ch2Error {
            get {
                return ((decimal)(this["Sc5Ch2Error"]));
            }
            set {
                this["Sc5Ch2Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc6Ch2Error {
            get {
                return ((decimal)(this["Sc6Ch2Error"]));
            }
            set {
                this["Sc6Ch2Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc1Ch3Error {
            get {
                return ((decimal)(this["Sc1Ch3Error"]));
            }
            set {
                this["Sc1Ch3Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc2Ch3Error {
            get {
                return ((decimal)(this["Sc2Ch3Error"]));
            }
            set {
                this["Sc2Ch3Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc3Ch3Error {
            get {
                return ((decimal)(this["Sc3Ch3Error"]));
            }
            set {
                this["Sc3Ch3Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc4Ch3Error {
            get {
                return ((decimal)(this["Sc4Ch3Error"]));
            }
            set {
                this["Sc4Ch3Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc5Ch3Error {
            get {
                return ((decimal)(this["Sc5Ch3Error"]));
            }
            set {
                this["Sc5Ch3Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc6Ch3Error {
            get {
                return ((decimal)(this["Sc6Ch3Error"]));
            }
            set {
                this["Sc6Ch3Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc1Ch5Error {
            get {
                return ((decimal)(this["Sc1Ch5Error"]));
            }
            set {
                this["Sc1Ch5Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc2Ch5Error {
            get {
                return ((decimal)(this["Sc2Ch5Error"]));
            }
            set {
                this["Sc2Ch5Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc3Ch5Error {
            get {
                return ((decimal)(this["Sc3Ch5Error"]));
            }
            set {
                this["Sc3Ch5Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc4Ch5Error {
            get {
                return ((decimal)(this["Sc4Ch5Error"]));
            }
            set {
                this["Sc4Ch5Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc5Ch5Error {
            get {
                return ((decimal)(this["Sc5Ch5Error"]));
            }
            set {
                this["Sc5Ch5Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc6Ch5Error {
            get {
                return ((decimal)(this["Sc6Ch5Error"]));
            }
            set {
                this["Sc6Ch5Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc1Ch6Error {
            get {
                return ((decimal)(this["Sc1Ch6Error"]));
            }
            set {
                this["Sc1Ch6Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc2Ch6Error {
            get {
                return ((decimal)(this["Sc2Ch6Error"]));
            }
            set {
                this["Sc2Ch6Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc3Ch6Error {
            get {
                return ((decimal)(this["Sc3Ch6Error"]));
            }
            set {
                this["Sc3Ch6Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc4Ch6Error {
            get {
                return ((decimal)(this["Sc4Ch6Error"]));
            }
            set {
                this["Sc4Ch6Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc5Ch6Error {
            get {
                return ((decimal)(this["Sc5Ch6Error"]));
            }
            set {
                this["Sc5Ch6Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Sc6Ch6Error {
            get {
                return ((decimal)(this["Sc6Ch6Error"]));
            }
            set {
                this["Sc6Ch6Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ScVersion {
            get {
                return ((int)(this["ScVersion"]));
            }
            set {
                this["ScVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsOnCalibration {
            get {
                return ((bool)(this["IsOnCalibration"]));
            }
            set {
                this["IsOnCalibration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MacVersion {
            get {
                return ((string)(this["MacVersion"]));
            }
            set {
                this["MacVersion"] = value;
            }
        }
    }
}
